<?php
/**
 * Created by PhpStorm.
 * User: Stefan
 * Date: 06.01.2018
 * Time: 16:37
 */

namespace stefan\ball;


class fussball extends ball
{

    private $typ = "Fussball";

    public function __construct($name, $durchmesser, $material)
    {
        parent::__construct($name, $durchmesser, $material);
    }


    public function __toString()
    {
        return 'Typ: '.$this->typ.' '.parent::__toString(); // TODO: Change the autogenerated stub
    }

}