<?php
/**
 * Created by PhpStorm.
 * User: Stefan
 * Date: 06.01.2018
 * Time: 16:40
 */

namespace stefan\ball;


class golfball extends ball
{
    private $typ = "Golfball";

    public function __construct($name, $durchmesser, $material)
    {
        parent::__construct($name, $durchmesser, $material);
    }

    public function __toString()
    {
        return parent::__toString(); // TODO: Change the autogenerated stub
    }


}